### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-react-template#1]
- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- fix README, package*, NOTICE/LICENSE
- ~~publish under `@marklogic-community`~~

**Comment by grtjn** [comment]
Fixed urls in .gitmodules as well, but didn't update to latest yet. (something i did do for the vue-template)

**Comment by grtjn** [comment]
as agreed, skipping deprecation message in bitbucket for now..

**Comment by mariannemyers** [comment]
This is complete.
