### ISSUE TITLE
Review branches

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-react-template#3]
I see 3 branches that don't seem linked to PR's:

I am sure there is vue support in cli, so pretty sure it can be deleted, though a little confused why it exists on the react-template.

add-tests seems like most recent updates. I recommend creating a WIP PR for that, creates visibility for it, and a way to add comments.

not sure about instantsearch-direct..

**Comment by patrickmcelwee** [comment]
I removed all branches except add-tests, and I opened PR #5 for that.

I left the instantsearch-direct branch in bitbucket for a bit of history (that we tried early on to use the instantsearch library, but found it not to be a suitable fit).
